### ISSUE TITLE
project user stories

### ISSUE THREAD

**Issue by britbrith4** [ga-dc/wdidc5-project3#15]
https://trello.com/b/G2imWe94/selfies-in-the-city

I use trello as a check list as well so sorry if that API one is confusing, it's not a user story.

**Comment by jshawl** [comment]
:+1: You're off to a good start Brittany!

I'm not sure I understand how the instagram api fits into your application. You have one user story that describes adding a photo - so be sure to add some functionality that is more than just a wrapper/interface around the instagram API. i.e. what does your application do that Instagram doesnt?

**Comment by britbrith4** [comment]
Yeah I think this weekend I ditched instagram and I'm going to use a
geocoder api and just create my own picture submission part

**Comment by jshawl** [comment]
Ok awesome! One thing to watch out for - heroku doesn't store user uploaded
content (like images) so if you want them to persist, you'll have to use
something like Amazon web services S3

On Sunday, May 10, 2015, britbrith4 notifications@github.com wrote:

> Yeah I think this weekend I ditched instagram and I'm going to use a
> geocoder api and just create my own picture submission part
> 
> On Sun, May 10, 2015 at 10:31 AM, Jesse Shawl <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
> 
> > [image: :+1:] You're off to a good start Brittany!
> > 
> > I'm not sure I understand how the instagram api fits into your
> > application. You have one user story that describes adding a photo - so
> > be
> > sure to add some functionality that is more than just a wrapper/interface
> > around the instagram API. i.e. what does your application do that
> > Instagram
> > doesnt?
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/ga-dc/wdidc5-project3/issues/15#issuecomment-100647213>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ga-dc/wdidc5-project3/issues/15#issuecomment-100653099
> .

## 

Jesse Shawl
http://jshawl.com
