### ISSUE TITLE
project #3

### ISSUE THREAD

**Issue by amaseda** [ga-dc/wdidc5-project3#20]
https://github.com/amaseda/tmw_me

**Comment by jshawl** [comment]
The board in your readme is private I believe - can you make public and reshare?

**Comment by amaseda** [comment]
Oops, should be public now. Going to modify the user stories too since the
idea has changed a little bit since Friday.

**Comment by jshawl** [comment]
:+1:  This seems like a really cool idea! I think it'd be awesome if users could create moments with a gif, or login with twitter or facebook - or both! 

I think the erd needs to be "published" to view as well.

**Comment by amaseda** [comment]
Published the ERD. And 100% yes to the GIFs. Decided to actually only let
people respond to "moments" with GIFs or images. Does the job a lot better
than text. Maybe even allow Vines too, but that's way down the line.

Really want to do Twitter/Facebook log-in, assuming I can wrap my head
around OAuth this week...
