### ISSUE TITLE
i could use some basic rails help

### ISSUE THREAD

**Issue by keithknox** [ga-dc/wdidc5-project3#40]
I'm having trouble creating an api call and i'm really stuck.  can anyone help?

**Comment by RobertAKARobin** [comment]
Genius Bar!

**Comment by keithknox** [comment]
i thought this was....my bad.

**Comment by jshawl** [comment]
also if you post code here that works too!

**Comment by jrhorn424** [comment]
@RobertAKARobin we've asked students to use github issues to practice describing their problem.

I discussed this with @keithknox and he's back on track. It wasn't clear how to use the object the Yelp client was returning.

**Comment by RobertAKARobin** [comment]
@jrhorn424 My bad!
