### ISSUE TITLE
Question about radio buttons

### ISSUE THREAD

**Issue by Tuzibun** [ga-dc/wdidc5-project3#42]
I'm trying to make a search form where users would select one of several radio buttons.  I want to make sure that if I use the code below, it will allow users to select only one button from each attribute category (i.e. they can't choose both male and female).  Some background: I want users to make selections of narrator characteristics so that I can query the database for narrators who fit that description.  Another thing is that I don't want to make any of the narrator characteristics required.  For example, they can choose just an accent they like, but not specify gender or whether or not the narrator does voices.

Here's the code:

<form>
  What would you like to hear?<br>
  <input type="radio" name="gender" id="male">Male<br>
  <input type="radio" name="gender" id="female">Female
</form>

<script>
function check() {
    document.getElementById("gender").checked = true;
}
function uncheck() {
    document.getElementById("gender").checked = false;
}
</script>

**Comment by RobertAKARobin** [comment]
This is built-in behavior of HTML. Give each mutually-exclusive radio button an identical `name` attribute:

```
<input type="radio" value="male" name="gender" />
<input type="radio" value="female" name="gender" />
```

**Comment by Tuzibun** [comment]
Perfect!  That's what I thought, but I got scared and thought maybe I was going crazy.
