### ISSUE TITLE
Join Table Not Saving (answer)

### ISSUE THREAD

**Issue by lmdragun** [ga-dc/wdidc5-project3#44]
I had a join table between User and Comic named User_Comic and it was not saving the Comic. 

In my comic_controller, when saving the comic, I could have just been saving user_comic, which would also save comic and save the comic_id to the User_Comic table.

Final code: 

``` ruby
    def create
        @comic = Comic.new(comic_params)
        @usercomic = current_user.user_comics.new(comic:@comic)
        byebug
        if @usercomic.save
            redirect_to @comic
        else
            render :new
        end
    end
```

**Comment by mattscilipoti** [comment]
1) I updated your comment.  Your code is now formatted via "```".
2) Do you want to create a new comic at the same time that you are assigning it to a user or are you selecting an existing Comic?

**Comment by lmdragun** [comment]
Right now I'm just creating a new comic when assigning it to the user, eventually I want both options.

**Comment by jrhorn424** [comment]
Thanks, @lmdragun!
