### ISSUE TITLE
project 3 sign in and signout issues

### ISSUE THREAD

**Issue by AliTopal89** [ga-dc/wdidc5-project3#45]
No route matches [GET] "/logout"
No route matches [GET] "/login" 

and many more

**Comment by AliTopal89** [comment]
`<li><%= link_to "Sign in", new_user_session_path %></li>
        <li><%= link_to "Sign Out", destroy_user_session_path %></li>`

**Comment by AliTopal89** [comment]
`devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}`

**Comment by RobertAKARobin** [comment]
http://stackoverflow.com/questions/6557311/no-route-matches-users-sign-out-devise-rails-3

**Comment by AliTopal89** [comment]
SOLVED ISSUE:
before: `<li><%= link_to "Sign Out", destroy_user_session_path %></li>`

after: `<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>`
