### ISSUE TITLE
When to choose Rails form and when to choose Javascript form?

### ISSUE THREAD

**Issue by lmdragun** [ga-dc/wdidc5-project3#47]
When is it better to use a Rails form for creation of new table entries and when is it better to use a Javascript form and create the entires through AJAX?

**Comment by jrhorn424** [comment]
It really comes down to whether you can handle a page refresh for your user experience.

If you choose to use an AJAX form, do not rely on client-side (JS) validation of data. Mirror any validations on the front-end in your rails models as well.

**Comment by jrhorn424** [comment]
@adambray Was this resolved?
