### ISSUE TITLE
having trouble passing in parameters through a rails form

### ISSUE THREAD

**Issue by greenes** [ga-dc/wdidc5-project3#48]
getting an error that the param is nil, but I have tried passing it in every way I can think of

**Comment by RobertAKARobin** [comment]
Show yer code!

**Comment by greenes** [comment]
in my profiles_controller i have:

```
  def update
      @profile = Profile.find( params[:id] )
      @artist = Artist.find(@profile.artist_id)
    if @profile.update( profile_params )
      redirect_to @profile
    else
      render :edit
    end

  end

```

here is the form in the profile edit view:

```
<%= form_for [@artist, @profile] do |f| %>
  <p>
  <%= f.label :name %>
  <%= f.text_field :name  %>
  </p>

  <p>
  <%= f.label :profile %>
  <%= f.text_area :profile %>
  </p>

  <%= f.hidden_field :artist_id, :value => @artist.id %>

  <p>
  <%= f.submit %>
  </p>

<%end%>

```

**Comment by jshawl** [comment]
does the nil param refer to a line number? is it `Profile.find( params[:id] )` that's failing?

**Comment by greenes** [comment]
it is pointing to the first line of the form and saying that the first argument of the form cannot be nil, but it is also saying that artist_id: = 1 and id = 1 as the params that are coming through

**Comment by jrhorn424** [comment]
I think this is a strong params issue. You've got `profile_params`. Is there a profile id in that object?

```
@profile = Profile.find( params[:id] )
# becomes
@profile = Profile.find(profile_params[:id])
# or maybe
 @profile = Profile.find(profile_params[:profile_id])
```

**Comment by jrhorn424** [comment]
> it is pointing to the first line of the form and saying that the first argument of the form cannot be nil, but it is also saying that artist_id: = 1 and id = 1 as the params that are coming through

Yes, that means either `@artist` or `@profile` is `nil`... the problem is then in the controller. It's passing a `nil` object to the view.

**Comment by greenes** [comment]
i added :id to the profile strong params, and tried both of those profile_params items, but it is still giving the same error

**Comment by jrhorn424** [comment]
Can you dump the params? Show me what is inside `profile_params` during a request?

**Comment by greenes** [comment]
this is what comes through:

Request
Parameters:
{"artist_id"=>"1",
 "id"=>"1"}

**Comment by jrhorn424** [comment]
The resolution was to create a controller action (`ProfilesController::Edit`) that instantiated both `@artist` and `@profile`.
