### ISSUE TITLE
When you have to use Rails to search an API, but want to choose among results in Javascript

### ISSUE THREAD

**Issue by lmdragun** [ga-dc/wdidc5-project3#49]
My API has a secret key, so I have to use Rails for it, but it also limits the amount of results, so to do a search I'd have to do the search directly in Rails.

I want to have multiple results from those searches appear and allow users to choose one (possibly through Javascript). Then I was thinking I could use Javascript to send that back to Rails, creating a new entry in a table. I'm having trouble with the logic for that, how to set up the search form/result listings/etc..

**Comment by jrhorn424** [comment]
Would it be possible to flip the logic of what you're attempting? I'd try to have Rails take care of all the requests first, build up a nice object or hash and then serialize that as JSON when requested by the front-end. That way, all your access and data-cleaning logic stay in one place, the back-end, and using the data is the responsibility of the client (the front-end).

**Comment by jrhorn424** [comment]
@lmdragun Is this resolved?
