### ISSUE TITLE
Having trouble importing data from CSV into postgres

### ISSUE THREAD

**Issue by mugshepherd** [ga-dc/wdidc5-project3#50]
It doesn't like that there are the timestamp columns in the database table when I try to bring in the data.  Thanks in advance!

**Comment by jrhorn424** [comment]
If you look at your schema or your migrations, you'll see that those timestamp columns cannot be null. You should be creating objects through rails and then persisting them to the database. So for example:

```
# suppose `data` holds our csv object, `row` is a hash with keys that match our table columns, and that Foo is an ActiveRecord object
data.each |row| do
  Foo.create!(row)
end
```

**Comment by jrhorn424** [comment]
Can you also please post your import code?

**Comment by mattscilipoti** [comment]
FYI: Toby is out today (planned family event).  He may not respond until tonight/tomorrow.

**Comment by mugshepherd** [comment]
Hi all - the import code is included in the rake file, which is referenced at bottom in the readme. I was able to take care of this so will close this issue when I return to DC this evening (please also feel free to close as well).  Thanks.
