### ISSUE TITLE
Undefined method `user_posts_path' error

### ISSUE THREAD

**Issue by JYamauchi** [ga-dc/wdidc5-project3#51]
I am trying to develop the user account system. Right now, I am trying to test it out by looking at posts on the profile view. I am not sure what does this mean? 

Error message:
undefined method `user_posts_path' for #<#Class:0x007fe8599a1548:0x007fe85db64390>

<h1>Listing your posts</h1>

<% if current_user %>
<%= form_for([current_user, current_user.posts.build]) do |f| %>
  <p>
    <%= f.label :body %><br>
    <%= f.text_field :body %>

**Comment by jrhorn424** [comment]
Please post your `rake routes` output.

**Comment by JYamauchi** [comment]
`Prefix Verb   URI Pattern                                Controller#Action
                    root GET    /                                          profiles#index
        new_user_session GET    /users/sign_in(.:format)                   devise/sessions#new
            user_session POST   /users/sign_in(.:format)                   devise/sessions#create
    destroy_user_session DELETE /users/sign_out(.:format)                  devise/sessions#destroy
           user_password POST   /users/password(.:format)                  devise/passwords#create
       new_user_password GET    /users/password/new(.:format)              devise/passwords#new
      edit_user_password GET    /users/password/edit(.:format)             devise/passwords#edit
                         PATCH  /users/password(.:format)                  devise/passwords#update
                         PUT    /users/password(.:format)                  devise/passwords#update
cancel_user_registration GET    /users/cancel(.:format)                    registrations#cancel
       user_registration POST   /users(.:format)                           registrations#create
   new_user_registration GET    /users/sign_up(.:format)                   registrations#new
  edit_user_registration GET    /users/edit(.:format)                      registrations#edit
                         PATCH  /users(.:format)                           registrations#update
                         PUT    /users(.:format)                           registrations#update
                         DELETE /users(.:format)                           registrations#destroy
                comments GET    /comments(.:format)                        comments#index
                         POST   /comments(.:format)                        comments#create
             new_comment GET    /comments/new(.:format)                    comments#new
            edit_comment GET    /comments/:id/edit(.:format)               comments#edit
                 comment GET    /comments/:id(.:format)                    comments#show
                         PATCH  /comments/:id(.:format)                    comments#update
                         PUT    /comments/:id(.:format)                    comments#update
                         DELETE /comments/:id(.:format)                    comments#destroy
                   posts GET    /posts(.:format)                           posts#index
                         POST   /posts(.:format)                           posts#create
                new_post GET    /posts/new(.:format)                       posts#new
               edit_post GET    /posts/:id/edit(.:format)                  posts#edit
                    post GET    /posts/:id(.:format)                       posts#show
                         PATCH  /posts/:id(.:format)                       posts#update
                         PUT    /posts/:id(.:format)                       posts#update
                         DELETE /posts/:id(.:format)                       posts#destroy
                  videos GET    /videos(.:format)                          videos#index
                         POST   /videos(.:format)                          videos#create
               new_video GET    /videos/new(.:format)                      videos#new
              edit_video GET    /videos/:id/edit(.:format)                 videos#edit
                   video GET    /videos/:id(.:format)                      videos#show
                         PATCH  /videos/:id(.:format)                      videos#update
                         PUT    /videos/:id(.:format)                      videos#update
                         DELETE /videos/:id(.:format)                      videos#destroy
                  photos GET    /photos(.:format)                          photos#index
                         POST   /photos(.:format)                          photos#create
               new_photo GET    /photos/new(.:format)                      photos#new
              edit_photo GET    /photos/:id/edit(.:format)                 photos#edit
                   photo GET    /photos/:id(.:format)                      photos#show
                         PATCH  /photos/:id(.:format)                      photos#update
                         PUT    /photos/:id(.:format)                      photos#update
                         DELETE /photos/:id(.:format)                      photos#destroy
      user_profile_index GET    /users/:user_id/profile(.:format)          profile#index
                         POST   /users/:user_id/profile(.:format)          profile#create
        new_user_profile GET    /users/:user_id/profile/new(.:format)      profile#new
       edit_user_profile GET    /users/:user_id/profile/:id/edit(.:format) profile#edit
            user_profile GET    /users/:user_id/profile/:id(.:format)      profile#show
                         PATCH  /users/:user_id/profile/:id(.:format)      profile#update
                         PUT    /users/:user_id/profile/:id(.:format)      profile#update
                         DELETE /users/:user_id/profile/:id(.:format)      profile#destroy
                   users GET    /users(.:format)                           users#index
                         POST   /users(.:format)                           users#create
                new_user GET    /users/new(.:format)                       users#new
               edit_user GET    /users/:id/edit(.:format)                  users#edit
                    user GET    /users/:id(.:format)                       users#show
                         PATCH  /users/:id(.:format)                       users#update
                         PUT    /users/:id(.:format)                       users#update
                         DELETE /users/:id(.:format)                       users#destroy`

**Comment by JYamauchi** [comment]
sorry it looks messy. I don't know how to straight it up as aligned.
