### ISSUE TITLE
Facebook/Twitter Omni_auth

### ISSUE THREAD

**Issue by DamonMd** [ga-dc/wdidc5-project3#52]
What is the easiest way to access the information that comes along with a user signed into my website with facebook/twitter(email, name, etc)?

I have a user model set up with just a few attributes(matching jesse's example from the class yesterday). Should i just create more attributes in my user model and and pull the info from the request.env["omniauth.auth"] hash in that user model file? And would I need to create columns in my schema/migration for these new attributes?

thanks,
damon

**Comment by jrhorn424** [comment]
I've never implemented OAuth myself, but I would have guessed that an OAuth gem would take care of this for you. Are you trying to do this on your own or are you using a gem?

**Comment by DamonMd** [comment]
using a gem, the information is returned in a hash. just having a bit of trouble accessing it

**Comment by DamonMd** [comment]
i'm thinking i just need to create more columns/attributes for my psql table because i'll run into issues with  active record if i try to create a new user with all the info i want from Facebook if those columns don't exist already

**Comment by mattscilipoti** [comment]
I sounds like you would like to save additional information about your user (beyond what is require by OAuth).  If that is the case, then yes, you need to addd columns, assign those values to the model's attributes, and persist them.

**Comment by jrhorn424** [comment]
I'll also note that you should not change your `schema.rb` directly. Only use migrations. Migrations update the schema (and will overwrite it). @DamonMd can this be closed?
