### ISSUE TITLE
I want to be able to save search data to a new database

### ISSUE THREAD

**Issue by Tuzibun** [ga-dc/wdidc5-project3#55]
I created a model for searches, but I'm not sure how to collect the search data and also run the search at the same time...  Probably just need some help with the logic... I hope

**Comment by mattscilipoti** [comment]
I expect that you want to you want to change the controller action to create a Search and then perform the search and process regularly.

**Comment by jrhorn424** [comment]
Yes, seems like you just need a form. Forms are we send data to the server. Then the controller action that receives the form will process the search and redirect to a results page with the appropriate data (instance variable) available to the results template.

**Comment by mattscilipoti** [comment]
Solved at genius bar.  She realized that she didn't need to save the searches.  We added filters to narrators#index.
