### ISSUE TITLE
when I add an API, the user authentication isn't working properly 

### ISSUE THREAD

**Issue by AliTopal89** [ga-dc/wdidc5-project3#56]
The errror message is: `ActiveRecord::RecordNotUnique in Welcome#index`

**Comment by mattscilipoti** [comment]
This doesn't sound like it has anything to do with user auth.  Please share the line that raises the error.

**Comment by AliTopal89** [comment]
`def create_guest_user
    u = User.create(:username => "guest", :email => "guest_#{Time.now.to_i}#{rand(100)}@example.com")
    u.save!(:validate => false)
    session[:guest_user_id] = u.id
    u
  end`

**Comment by AliTopal89** [comment]
```
def create_guest_user
    u = User.create(:username => "guest", :email => "guest_#{Time.now.to_i}#{rand(100)}@example.com")
    u.save!(:validate => false)
    session[:guest_user_id] = u.id
    u
  end
```

**Comment by AliTopal89** [comment]
ok nevermind got it fixed

**Comment by jrhorn424** [comment]
What was the resolution?

**Comment by mattscilipoti** [comment]
In the future, please use "Preview" to ensure your code is formatted as code.  I changed your last code example to use three backticks (```).  You can see how much easier it is to read.
