### ISSUE TITLE
Heroku Error: "Push rejected, no Cedar-supported app detected"

### ISSUE THREAD

**Issue by philw214** [ga-dc/wdidc5-project3#60]
Currently looking through the Heroku link provided in the error, but still stuck.
![screen shot 2015-05-13 at 1 57 36 pm](https://cloud.githubusercontent.com/assets/11447889/7617278/1e5a1132-f978-11e4-97fc-c7d297f7fd68.png)

**Comment by RobertAKARobin** [comment]
Your `.git` has to be in the same directory as your Gemfile and the rest of your app. If it isn't, go up to directory that contains `.git` and run this:

`git subtree push --prefix theNameOfTheDirectoryContainingYourGemfile heroku master`

**Comment by philw214** [comment]
that worked. THANKS!
