### ISSUE TITLE
ajax patch request to my rails app

### ISSUE THREAD

**Issue by greenes** [ga-dc/wdidc5-project3#62]
I am having trouble figuring out how to get model parameters into my javascript code from my ruby code so i can make a request like this:

```
  update: function(){
    $.ajax({
      type: 'PATCH',
      data: { piece: {stars: this.stars + 1}},
      dataType: 'json',
      url: 'http://localhost:3000/artists/' + this.artist + '/galleries/' + this.gallery + '/pieces' + this.id
    }).done(function(response) {
      console.log("ajax request complete");
      console.log(response);
    }).fail(function(){
      console.log("failed to save");
    })
  }
```

**Comment by jshawl** [comment]
I would render a form in HTML server side:

``` html
<form>
  <input type='hidden' value='someparamthatyouneedinjavascript'>
</form>
```

Then whatever calls your `update` method in your js can grab the values from that form.

**Comment by greenes** [comment]
ok great, I will try that, thanks!

**Comment by jrhorn424** [comment]
The problem was a missing trailing slash in the AJAX URL.

**Comment by greenes** [comment]
And I was able to use an ajax 'get' request to access the piece model parameters I need for the patch request
