### ISSUE TITLE
Add event listener to autocomplete search

### ISSUE THREAD

**Issue by chadxsmith** [ga-dc/wdidc5-project3#63]
When users search for a particular question, my autocomplete displays available options. I'm attempting to add an event listener on each result, and save the clicked item into a variable.

var content ;

$(".ui-menu-item", this).click(function(){
    var content = $(".ui-menu-item").html();
})

console.log(content)

**Comment by jshawl** [comment]
can you console.log anything in the event listener?

If not, what if you try:

``` js
$("body").on("click", ".ui-menu-item", function()...)
```

**Comment by adambray** [comment]
Closed in person.
