### ISSUE TITLE
Devise ORM Issue

### ISSUE THREAD

**Issue by luminousbeam** [ga-dc/wdidc5-project3#64]
I followed both <a href="http://andrewsunglaekim.github.io/Getting-a-handle-on-devise/">Andy's blog</a> instructions on how to install devise and the <a href="http://guides.railsgirls.com/devise/">Rails Girls guide</a> more recently.  After following these instructions, I get the error I have pasted right below them:

Git CL:
   rails g devise user
# I noticed that I do not have a devise.rb file within config/initializers and I would add one manually, except I'm not sure what content should be in the file.

Error:
/Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/devise-3.4.1/lib/devise/rails/routes.rb:490:in `raise_no_devise_method_error!': User does not respond to 'devise' method. This usually means you haven't loaded your ORM file or it's being loaded too late. To fix it, be sure to require 'devise/orm/YOUR_ORM' inside 'config/initializers/devise.rb' or before your application definition in 'config/application.rb' (RuntimeError)

```
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/devise-3.4.1/lib/devise/rails/routes.rb:227:in `block in devise_for'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/devise-3.4.1/lib/devise/rails/routes.rb:223:in `each'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/devise-3.4.1/lib/devise/rails/routes.rb:223:in `devise_for'
from /Users/luminousbeam/Documents/other_dev/project3/blog/config/routes.rb:5:in `block in <top (required)>'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:432:in `instance_exec'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:432:in `eval_block'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/actionpack-4.2.1/lib/action_dispatch/routing/route_set.rb:410:in `draw'
from /Users/luminousbeam/Documents/other_dev/project3/blog/config/routes.rb:1:in `<top (required)>'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `block in load'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:268:in `load'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:40:in `each'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:40:in `load_paths'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:16:in `reload!'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:26:in `block in updater'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.1/lib/active_support/file_update_checker.rb:75:in `call'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.1/lib/active_support/file_update_checker.rb:75:in `execute'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:27:in `updater'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/railties-4.2.1/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/railties-4.2.1/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `instance_exec'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:30:in `run'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:55:in `block in run_initializers'
from /Users/luminousbeam/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:226:in `block in tsort_each'
from /Users/luminousbeam/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
from /Users/luminousbeam/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:429:in `each_strongly_connected_component_from'
from /Users/luminousbeam/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:347:in `block in each_strongly_connected_component'
from /Users/luminousbeam/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each'
from /Users/luminousbeam/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `call'
from /Users/luminousbeam/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:345:in `each_strongly_connected_component'
from /Users/luminousbeam/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:224:in `tsort_each'
from /Users/luminousbeam/.rvm/rubies/ruby-2.2.0/lib/ruby/2.2.0/tsort.rb:203:in `tsort_each'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/railties-4.2.1/lib/rails/initializable.rb:54:in `run_initializers'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/railties-4.2.1/lib/rails/application.rb:352:in `initialize!'
from /Users/luminousbeam/Documents/other_dev/project3/blog/config/environment.rb:5:in `<top (required)>'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/spring-1.3.6/lib/spring/application.rb:92:in `preload'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/spring-1.3.6/lib/spring/application.rb:143:in `serve'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/spring-1.3.6/lib/spring/application.rb:131:in `block in run'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/spring-1.3.6/lib/spring/application.rb:125:in `loop'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/spring-1.3.6/lib/spring/application.rb:125:in `run'
from /Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/spring-1.3.6/lib/spring/application/boot.rb:18:in `<top (required)>'
from /Users/luminousbeam/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from /Users/luminousbeam/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
from -e:1:in `<main>'
```

**Comment by jshawl** [comment]
have you done `rails g devise:install`?

**Comment by luminousbeam** [comment]
Heya, yes, I did that step prior to using "rails g devise user", that command gives me this error: 

Jocelyns-MacBook-Air:blog luminousbeam$ rails g devise:install
/Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/devise-3.4.1/lib/devise/rails/routes.rb:490:in `raise_no_devise_method_error!': User does not respond to 'devise' method. This usually means you haven't loaded your ORM file or it's being loaded too late. To fix it, be sure to require 'devise/orm/YOUR_ORM' inside 'config/initializers/devise.rb' or before your application definition in 'config/application.rb' (RuntimeError)

**Comment by luminousbeam** [comment]
I should add that devise seems to have installed, but perhaps incorrectly.  It created a user model and a devise_create_users.rb file under db/migrations.

**models/user.rb:**

class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

**db/migrate/20150513163233_devise_create_users.rb:**

class DeviseCreateUsers < ActiveRecord::Migration
  def change
    create_table(:users) do |t|
      ## Database authenticatable
      t.string :email,              null: false, default: ""
      t.string :encrypted_password, null: false, default: ""

```
  ## Recoverable
  t.string   :reset_password_token
  t.datetime :reset_password_sent_at

  ## Rememberable
  t.datetime :remember_created_at

  ## Trackable
  t.integer  :sign_in_count, default: 0, null: false
  t.datetime :current_sign_in_at
  t.datetime :last_sign_in_at
  t.inet     :current_sign_in_ip
  t.inet     :last_sign_in_ip

  ## Confirmable
  # t.string   :confirmation_token
  # t.datetime :confirmed_at
  # t.datetime :confirmation_sent_at
  # t.string   :unconfirmed_email # Only if using reconfirmable

  ## Lockable
  # t.integer  :failed_attempts, default: 0, null: false # Only if lock strategy is :failed_attempts
  # t.string   :unlock_token # Only if unlock strategy is :email or :both
  # t.datetime :locked_at


  t.timestamps
end

add_index :users, :email,                unique: true
add_index :users, :reset_password_token, unique: true
# add_index :users, :confirmation_token,   unique: true
# add_index :users, :unlock_token,         unique: true
```

  end
end

**Comment by jrhorn424** [comment]
Try doing `bundle exec rails generate devise:install` followed by `bundle exec rails generate devise User`.

**Comment by luminousbeam** [comment]
*_I just tried that and got this error: *_
Jocelyns-MacBook-Air:blog luminousbeam$ bundle exec rails generate devise:install
/Users/luminousbeam/.rvm/gems/ruby-2.2.0/gems/activerecord-4.2.1/lib/active_record/dynamic_matchers.rb:26:in `method_missing': undefined method`devise' for User (call 'User.connection' to establish a connection):Class (NoMethodError)
    from /Users/luminousbeam/Documents/other_dev/project3/blog/app/models/user.rb:4:in `<class:User>'
    from /Users/luminousbeam/Documents/other_dev/project3/blog/app/models/user.rb:1:in`<top (required)>'

**Comment by andrewsunglaekim** [comment]
have you added "devise" to the gem file, and have you run a `bundle install`?

**Comment by luminousbeam** [comment]
@andrewsunglaekim that was one of the first things i did! Jesse got me to delete some stuff and to re-install devise.  It allowed me to sign up but it did not let me use my login information to actually create a new blog post (my project is in a blog format) even though it says that I am currently logged in!

**Comment by andrewsunglaekim** [comment]
im not clear what the problem is at this moment, what do you mean by `use my login information to actually create a new blog post`?

**Comment by luminousbeam** [comment]
![authentication_req](https://cloud.githubusercontent.com/assets/9014849/7635467/30b1540a-fa2f-11e4-835a-35c59cb7ec7e.png)

I signed up and created a login using an email and a password, my rails app logged me in.  When I go to create a new post it is popping up the "Authentication Required" box and when I re-enter my login info, it is not taking it and essentially denying me access.

**Comment by andrewsunglaekim** [comment]
This isn't the normal behavior of the devise gem, did you do anything else to the user auth in your application?

**Comment by luminousbeam** [comment]
i see what i did!  initially i had added this to the comments controller: 
http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy and this to the articles controller:
http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show].

i commented those out and it's working now, thanks.
