### ISSUE TITLE
ImageMagick 

### ISSUE THREAD

**Issue by KMG112** [ga-dc/wdidc5-project3#65]
Im trying to use Imagemagick, but Im having some issues understanding how to print out a collection of images that have been placed into an imageList. my images are coming from APIs, and I am able to collect them but making them appear on the show page is proving difficult

**Comment by jrhorn424** [comment]
What are you using imagemagick for? It sounds like what you're trying to do is show a bunch of images on a page. If that's the case, it's similar to how you might display other data. You just need to have references to them in your database. For example:

```
# assume Picture is an AR model, and the @pictures collection is created by the controller
# in the view:
@pictures.each do |picture|
  image_tag @picture.url
end
```

**Comment by KMG112** [comment]
Im eventually trying to compile the images into a new image, but I thought that a good first step for understanding how to deal with the compiled images in an imageList was to first be able to display each image.

**Comment by jshawl** [comment]
https://github.com/jshawl/image-magick-example-rb
