### ISSUE TITLE
figaro and heroku issue...

### ISSUE THREAD

**Issue by hharper** [ga-dc/wdidc5-project3#67]
i cannot deploy because heroku cannot read my API keys since I hid them with figaro gem...do I have to define them in my terminal manually? I didn't have to do this on last project...there was a rake command I used but looks like no longer active? HALP

I believe I used rake figaro: heroku but now not working...

so I tried this instead: 
$ figaro heroku:set -e production but thats not working either...

**Comment by RobertAKARobin** [comment]
What kind of error are you getting?

**Comment by hharper** [comment]
i was getting: 

 !    No app specified.
 !    Run this command from an app folder or specify which app to use with --app APP.

but figured it out now. I think i was having issues because my .git was a parent of my app, so I did the prefix thing you recommended and trying to figure out now...

**Comment by RobertAKARobin** [comment]
Well, good! Can I close this bad boy?

**Comment by hharper** [comment]
Yes!
