### ISSUE TITLE
w08d04-HW-JM-Project3

### ISSUE THREAD

**Issue by tsetoung** [ga-dc/wdidc5-project3#7]
https://github.com/tsetoung/DriveS

**Comment by adambray** [comment]
Hey John,

Since we talked about this in person on Friday, I'm going to go ahead and close this! Please make sure to have your ERD and other documentation updated by tomorrow at 5pm. 

Let's also chat again some time tomorrow to review where you're at and see if I can help at all!

-Adam

**Comment by jrhorn424** [comment]
@tsetoung Let's also plan on talking about this on Monday. @adambray can join, too if he likes.
