### ISSUE TITLE
AWS

### ISSUE THREAD

**Issue by britbrith4** [ga-dc/wdidc5-project3#70]
I have to use Amazon Web Services because I am using a photo uploader. I created an account and have my key in the correct (i think) places in my rails app. I can select I file to upload but when I select submit it goes to a blank page. I called the image in my show page so SOMETHING should be showing up. I am getting an error in Amazon web services for the key it's saying it is not valid but I have generated a new key a few times and copied it directly. Any ideas?

**Comment by britbrith4** [comment]
Also I have gone to the show page and inspected the element for the image and it says that the amazon key has an error.

**Comment by mattscilipoti** [comment]
Please share the specific error.

**Comment by nclevine** [comment]
brittany, are you indicating the right bucket? when i used aws s3 for my last project that was something we had to do. there's like the key, the token, and the bucket name (the bucket you are using to store the images specific to whatever site you're working on)

**Comment by britbrith4** [comment]
Yes i indicated it. I got it working now I guess Parmeet helped me figure it out thanks a lot though
