### ISSUE TITLE
figaro env variables not working

### ISSUE THREAD

**Issue by nclevine** [ga-dc/wdidc5-project3#75]
I have figaro installed, all of my keys are defined in the application.yml file and i'm using ENV['my_key'] in string interpolation in the controllers ... it seems that ENV[ ... ] isn't actually loading the keys because the error i'm getting at runtime is that the API key is missing ... i have rails 12 factor gem installed and i got rid spring, but it's still not working

**Comment by jshawl** [comment]
Did you try restarting the server?

**Comment by jshawl** [comment]
Also you can see all environment variables by opening up `rails c` and typing `ENV`

**Comment by nclevine** [comment]
thanks i didn't think of restarting the server- it's working now!
