### ISSUE TITLE
My API is not showing on Heroku

### ISSUE THREAD

**Issue by AliTopal89** [ga-dc/wdidc5-project3#76]
I deployed my app to Heroku and the API is not showing in the posts page. Where it should be. 
- Also, the changes I made with CSS on the first page is not showing either, but my main concern is the API

**Comment by jshawl** [comment]
Is the api call in javascript or ruby? If the api call is in javascript, are there any errors in the console?

**Comment by AliTopal89** [comment]
errors is the console is that the leaflet API and the leaflet CSS is untrusted sources

**Comment by AliTopal89** [comment]
I'm trying to figure that out now

**Comment by jshawl** [comment]
ah check out this issue - https://github.com/ga-dc/wdidc5-project3/issues/72

**Comment by AliTopal89** [comment]
![screen shot 2015-05-14 at 3 16 01 pm](https://cloud.githubusercontent.com/assets/9599485/7639770/66c8b9bc-fa4c-11e4-9588-31ecba577267.png)

**Comment by AliTopal89** [comment]
I don't know if the error is same from issue #72

**Comment by RobertAKARobin** [comment]
Where the heck did you get that? What's leafletjs.com?

**Comment by AliTopal89** [comment]
my API

**Comment by AliTopal89** [comment]
it's giving me this error in the console in heroku net::ERR_INSECURE_RESPONSE

**Comment by RobertAKARobin** [comment]
Oh. It's because you're trying to do `https` to a site that's just `http`.

**Comment by AliTopal89** [comment]
matt and I already changed that, can I please show this error to you. Visually it might make more sense I feel like. Are you available at the moment?

**Comment by RobertAKARobin** [comment]
Nope. Copy and paste it!

**Comment by RobertAKARobin** [comment]
Never once have I had an error that made more sense visually. This is code we're talking about, not pictures.

**Comment by AliTopal89** [comment]
![screen shot 2015-05-14 at 3 36 26 pm](https://cloud.githubusercontent.com/assets/9599485/7640083/1d162d9c-fa4f-11e4-81f6-15f149f46845.png)

**Comment by AliTopal89** [comment]
ok I just accepted the API risks, hopefully I don't get charged 10000000000000 dollars for it
