### ISSUE TITLE
rails not rendering json

### ISSUE THREAD

**Issue by nclevine** [ga-dc/wdidc5-project3#77]
here is the method i am calling:

```
def search
    search_term = params[:keyword]
    url = "http://www.vam.ac.uk/api/json/museumobject/search?images=1&q=#{search_term}"
    @response = HTTParty.get(url)
    render json: @response
end
```

it isn't returning anything. when i manually go to the url `victoriaalbert?keyword=sculpture` to simulate a call to the method, i get this `content-typecontent-lengthconnectiondateviavaryx-ua-compatibleserver` the same structure of code is used for my other apis and it works fine. also if i write `render json: @response.to_json` it actually loads the response, just formatted like crap with `\n` everywhere

**Comment by jshawl** [comment]
what if you just `render @response`? It's already JSON from the api I believe

**Comment by nclevine** [comment]
i get an argument error from rails if i do that

**Comment by nclevine** [comment]
still not working if someone else has any suggestions :( thanks!

**Comment by RobertAKARobin** [comment]
What's the argument error, Noah? Also, try `puts @response` to see it in your server log (the stuff that changes in your terminal when you go to a new page or whatever). If you can't see it in your log, try putting `puts 123456789` or something.

**Comment by nclevine** [comment]
the argument error is a huge string of the HTTParty response

**Comment by nclevine** [comment]
if i do `puts @response` as you suggest, i can see the json that should be rendering ... except it's not

**Comment by nclevine** [comment]
`puts @response.class` returns `HTTParty::Response`

**Comment by RobertAKARobin** [comment]
Can you paste the text of the error?

**Comment by nclevine** [comment]
there is no error unless i omit `json:`

**Comment by RobertAKARobin** [comment]
It's just blank?

**Comment by nclevine** [comment]
the page is blank and no error is thrown

**Comment by nclevine** [comment]
the only time it throws the argument error is if i omit `json:`

**Comment by nclevine** [comment]
otherwise the line `render json: @repsonse` gives me `content-typecontent-lengthconnectiondateviavaryx-ua-compatibleserver`

**Comment by nclevine** [comment]
which doesn't break my program, but it doesn't turn into anything useful in my site

**Comment by nclevine** [comment]
it's like the response never existed

**Comment by RobertAKARobin** [comment]
Give this a whirl:

```
@response = HTTParty.get("URL").parsed_response
```

**Comment by RobertAKARobin** [comment]
My inspiration: http://stackoverflow.com/questions/20448171/how-do-i-get-and-display-json-with-httparty

**Comment by nclevine** [comment]
huzzah!

**Comment by nclevine** [comment]
thank you very much!

**Comment by nclevine** [comment]
not sure why that one out of all of them requires that extra method, but cool -_-

**Comment by RobertAKARobin** [comment]
Such is life!
