### ISSUE TITLE
Rails Drop Down List

### ISSUE THREAD

**Issue by JYamauchi** [ga-dc/wdidc5-project3#78]
I am trying to make a drop down list to select the type of posts, each type of posts has different methods such as importing images/videos, search the key tag before making a post, or just plain text. My question is for example, when I select the option= "search giphy", how do I make the selection form to create or summon the form as it should show only the search box instead of showing the form where the user can paste the image's url like switching different forms. 

here is my code for the drop down list:
`<select name="post-option">
      <option value="">Please select</option>
      <option value="1" selected="selected">Simple Text</option>
      <option value="2">Giphy Slideshow</option>
      <option value="3">Import Images</option>
      <option value="4">Import Video</option>
    </select>`

**Comment by JYamauchi** [comment]
<select name="post-option">
      <option value="">Please select</option>
      <option value="1" selected="selected">Simple Text</option>
      <option value="2">Giphy Slideshow</option>
      <option value="3">Import Images</option>
      <option value="4">Import Video</option>
    </select>

**Comment by jshawl** [comment]
> when I select the option= "search giphy", how do I make the selection form

Start by adding a console.log() when the user selects an option.

**Comment by JYamauchi** [comment]
Oh I mean when I select the option, it should render like "_form1" or "_form2" or "_form3". like refer to the path.

**Comment by jshawl** [comment]
are you loading each of those forms on the initial page load?

If so, you can hide all of them, and only display the relevant form when the user selects one of the dropdown items
