### ISSUE TITLE
Ajax patch request not working after deploying Heroku

### ISSUE THREAD

**Issue by greenes** [ga-dc/wdidc5-project3#79]
I want to increase the number of "likes" a painting has. it was working on my local host. But now in heroku the number increases on the page, but if i leave the page and come back, the number is back to 0. Here is the code:

```
  update: function(){
    $.ajax({
      type: 'PATCH',
      data: { piece:
        {
          id: this.id,
          gallery_id: this.gallery,
          stars: this.hearts
        }
      },
      dataType: 'json',
      url: '/artists/' + this.artist + '/galleries/' + this.gallery + '/pieces/' + this.id
    }).done(function(response) {
      console.log("ajax request complete");
      console.log(response);
    }).fail(function(response){
      console.log("failed to save", response.responseText);
    })
  }
```

also tried this:

```
  update: function(){
    $.ajax({
      type: 'POST',
      dataType: 'script',
      url: '/artists/' + this.artist + '/galleries/' + this.gallery + '/pieces/' + this.id,
      contentType:'application/json',
      data: JSON.stringify({ piece:
        {
          id: this.id,
          gallery_id: this.gallery,
          stars: this.hearts
        },
        _method: 'put'
      }
    }).done(function(response) {
      console.log("ajax request complete");
      console.log(response);
    }).fail(function(response){
      console.log("failed to save", response.responseText);
    })
  }
```

**Comment by jshawl** [comment]
Are there any errors in the console?

**Comment by greenes** [comment]
When the page loads and when i click the like button it says : 

Mixed Content: The page at 'https://rocky-island-7589.herokuapp.com/artists/1/galleries/1/pieces/1' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://localhost:3000/artists/1/galleries/1/pieces/1'. This request has been blocked; the content must be served over HTTPS.

**Comment by andrewsunglaekim** [comment]
ooh, change anywhere you see `http://` to `https://` in your JS, see if that fixes it

**Comment by andrewsunglaekim** [comment]
additionally, it seems like your heroku app is pinging to your local host, it probably needs to not do that ...

**Comment by andrewsunglaekim** [comment]
Also read the dialogue from another one of your classmate's issues re: `https://github.com/ga-dc/wdidc5-project3/issues/72`

**Comment by adambray** [comment]
@greenes can you please update this or close the issue if you no longer need help? Thanks!
