### ISSUE TITLE
Run ajax on page load

### ISSUE THREAD

**Issue by presto2116** [ga-dc/wdidc5-project3#81]
Trying to find a way to run ajax on page load. I assume I need to put something in my application.js file after var gifView = new GifView(); but cant get anything to work

```
var ready = function ready () {
    $(document).foundation();
    var gifView = new GifView();
}

$(document).ready(ready);
$(document).on('page:load', ready);
```

**Comment by andrewsunglaekim** [comment]
the first line of your code is reading kinda funky. Shouldn't it be `var ready = function (){` Regardless, if you want the ajax to happen on page load, just do an `$.ajax` call at the top of your ready function definition.

**Comment by andrewsunglaekim** [comment]
I think we fixed your issue, open another issue if you run into another problem with this.

**Comment by jrhorn424** [comment]
@andrewsunglaekim That first line aids in debugging. Function expressions are great for hoisting issues, but they don't have names and cannot be called recursively.
