### ISSUE TITLE
erratic profile_path

### ISSUE THREAD

**Issue by uhhlittle** [ga-dc/wdidc5-project3#82]
Hi, 

I am having trouble with my profile model, that has a one to one relationship with the devise g model. 

I have a conditional in my layout.html.erb file like so

``` html
<ul class= "right">
      <% if current_user && current_user.profile %>
        <li><em><%= link_to "Welcome #{current_user.email}", 'profile_path'%></em></li>
        <li>  <%= link_to 'Signout', destroy_user_session_path, :method => :delete, class: "sign_out" %> </li>
        <li>  <%= link_to 'Profile', profile_path %> </li>

      <% elsif current_user %>
          <li><em><%= link_to "Welcome #{current_user.email}", '/profile'%></em></li>
          <li>  <%= link_to 'Signout', destroy_user_session_path, :method => :delete, class: "sign_out" %> </li>
      <% else %>
        <li>  <%= link_to "Sign up", new_user_registration_path, class: "sign_up" %> </li>
        <li>  <%= link_to "Login", new_user_session_path, class: "login" %> </li>
      <% end %>
    </ul>
```

and when i click on either link to the profile, it links me to data in profiles belonging to other users. different names, different locations etc. 

can you help??

**Comment by jshawl** [comment]
It's because you're linking to `profile_path`. What's the output of rake routes? I think you want something like `user_profile_path`

**Comment by uhhlittle** [comment]
my resources aren't nested, so I don't have a user_profile_path. BUT in my show route, I was calling Profile.find(params[:id]) and then i changed it to current_user.profile and things seem to be going better.

**Comment by andrewsunglaekim** [comment]
normally when you have a path with a singular (ie `profile_path`) you have to pass in an object (ie which profile)

**Comment by jshawl** [comment]
better as in issue fixed?

**Comment by uhhlittle** [comment]
I did end up needing to pass current_user.profile to the path, and now everything seems to be working

**Comment by uhhlittle** [comment]
Thanks!
