### ISSUE TITLE
uninitialized constant Search

### ISSUE THREAD

**Issue by chadxsmith** [ga-dc/wdidc5-project3#84]
When attempting to access my Search index page, I'm receiving an "Uninitialized Constant Search" error. I've checked the Controller (i.e. searches_controller.rb  | SearchesController < ApplicationController) and page linking to the Search index page, and I'm still receiving the  error. 

Any thoughts?

**Comment by RobertAKARobin** [comment]
Can you show the code for your `search` controller?

**Comment by chadxsmith** [comment]
class SearchesController < ApplicationController

```
  def index
    @question_query = params[:question]
  end
```

end

**Comment by jshawl** [comment]
what does `config/routes.rb` look like?

**Comment by chadxsmith** [comment]
Rails.application.routes.draw do

```
  root "languages#index"

  resources :languages do
    resources :topics do
      resources :questions do
        resource :answer

      end
    end
  end

 get "/search", to: "search/#index"
```

**Comment by RobertAKARobin** [comment]
That's what you posted last time, Chad. Can you show `/routes/config.rb`?

**Comment by RobertAKARobin** [comment]
Ah, there we go

**Comment by RobertAKARobin** [comment]
Try this:

```
 get "/search", to: "search#index"
```

**Comment by chadxsmith** [comment]
nice! the error's gone! but the page no longer refreshes, when clicking the submit button to go the search page

**Comment by chadxsmith** [comment]
nvm

**Comment by chadxsmith** [comment]
well, when i add the equal sign to:

```
 $("#submit").on("click", function() {
    window.location.assign('<%=search_path%>')
})
```

the error reappears

**Comment by RobertAKARobin** [comment]
The same error?

**Comment by chadxsmith** [comment]
the same type
