### ISSUE TITLE
Issues with Devise and Heroku

### ISSUE THREAD

**Issue by Freetown5** [ga-dc/wdidc5-project3#85]
So, I tried to deploy my app to Heroku but kept getting this error: 

remote:        Devise.secret_key was not set. Please add the following to your Devise initializer:
remote:        config.secret_key = '535188de5414e9255ee0e1c8e2d2a12cb9b3c9cadee4120ebc7e9aef5a887763d772a16006452ddf36b04b38d563b140ddf34d2d595a5058915a2895516b85c7'

tried adding the key to initializer page(among several other things) and I'm still getting the same error. How do I fix it?

**Comment by jshawl** [comment]
did you add and commit your changes, and then push to heroku again?

**Comment by Freetown5** [comment]
yes, I did still got the same error.
