### ISSUE TITLE
OOJ pulling single object from rails api

### ISSUE THREAD

**Issue by uhhlittle** [ga-dc/wdidc5-project3#87]
I used trillo as an example to model my js front end models. 

is there an example from an iteration where we just straight up called cards from the db? 

Also I am trying to create a fridge object on the front end but it doesn't have any data...and I'm confused about which data to summon. 

Also if someone could come actually talk to me about this in person I'd really appreciate it. 

Thank you.

**Comment by uhhlittle** [comment]
blergh i hate git issues. and i'm so tired.

clarifications: 'straight up called from the db' === without a js model

the fridge object does;t have any attributes to call in the data field...so what can I enter for it to pull from the db? right now I don't think i'm creating any kind of object.

**Comment by RobertAKARobin** [comment]
Sorry for the delay! We saw there was an additional comment on here and figured it was from an instructor. OK, figuring it out now...
