### ISSUE TITLE
More active record table issues

### ISSUE THREAD

**Issue by lmdragun** [ga-dc/wdidc5-project3#88]
So in order to list out information from a join table, I had to use ruby in the view. It worked. But I tried to use the same system for another part and can't get that to work.

Initial ruby:

``` rb
            <% ownership = c.ownerships.find_by(user_id: params[:id]) %>
                <% if ownership.favorite == true %>
                <span class="comic-fav"> f </span>
                <% end %>
```

Current attemp:

``` rb
                <% @this_loan = @loans.find_by(ownership_id: ownership.id) %>
                This loan: <%= @this_loan %>
                  <% if @this_loan.out == true %>
                    <%= @this_loan.lendee_id.name %>
                  <% end %>
```

"This loan: ..." pulls up the AR entry (with a lot of numbers, etc.). But the @this_loan.out part gives a nil error.

This would show whether or not a comic in the user's collection has been loaned out (a boolean column in the table called "out") and then preferably who it has been loaned out to.

**Comment by RobertAKARobin** [comment]
`@loans.find_by` looks suspicious. Try `Loan.find_by`?

Also, this is where Helpers come in handy. Just put something like this in there:

```
def find_loan(ownership_id)
  this_loan = Loans.find_by(ownership_id: ownership_id)
  if this_loan.out === true
    return this_loan.lendee_id.name
  end
end
```

Then in your view:

```
<%= find_loan(ownership_id: ownership.id) %>
```
