### ISSUE TITLE
cannot Center CSS

### ISSUE THREAD

**Issue by AliTopal89** [ga-dc/wdidc5-project3#89]
I'm trying to center the Css in my spots page only and whenever i make a change in spots page, it also changes it where I have it in posts. Hmm I'm lost

**Comment by jshawl** [comment]
https://css-tricks.com/centering-css-complete-guide/

**Comment by AliTopal89** [comment]
solution for it is to first validate your HTML at http://validator.w3.org/check and the next step was to put everything in the center and that was done by putting everything you want to center in the <main></main> + some CSS. If anyone wants to know I can walk them through the css or send it directly to them but I don't want to post 200 lines of CSS in this comment box. Cheers
