### ISSUE TITLE
Creating a dropdown menu from a table column

### ISSUE THREAD

**Issue by Tuzibun** [ga-dc/wdidc5-project3#91]
I am trying to create a drop down menu that is populated by my Narrators table.  I want the menu to show the narrators' names but send back the id to the database. Is there a way to do this?

This is the form right now:

<div class="newAudiobookFormBox">
    <%= form_tag "/audiobooks", method: :post do %>
    <h2>Add an Audiobook to listenUP</h2>

    <p class="formField">Title:</p>
    <%= text_field_tag :title, "Book title" %>
    <br>
    <p class="formField">Author:</p>
    <%= text_field_tag :author, "Author's full name" %>
    <br>
    <p class="formField">Category:</p>
    <%= select_tag :category, options_for_select(["Fantasy", "Classics", "Memoir", "Mystery", "History", "Business", "Self-Development", "Fiction", "Teens", "Kids", "Nonfiction"]) %>
    <br>

    <p class="formField">Narrator:</p>
    <%= select_tag :narrator_id, options_from_collection_for_select(@narrators, "id", "name") %>
    <br>
    
    <%= submit_tag "Submit" %>
    <% end %>

</div>

**Comment by RobertAKARobin** [comment]
I think I answered this in Slack! `<select>` elements are a lot like `input` elements. If you have:

```
<select name="fruit">
<option value="banana">Ban</option>
<option value="apple">Apl</option>
<select>
```

...and `Apl` is selected, when you click "Submit", `fruit=apple` will be included in the params of your request.

**Comment by Tuzibun** [comment]
I'm still getting this:
[image: Inline image 1]

I think it might be because I am trying to get to the narrators table from
the audiobooks new.html.erb??

On Thu, May 14, 2015 at 6:17 PM, Robert Thomas notifications@github.com
wrote:

> I think I answered this in Slack! <select> elements are a lot like input
> elements. If you have:
> 
> <select name="fruit">
> <option value="banana">Ban</option>
> <option value="apple">Apl</option>
> <select>
> 
> ...and Apl is selected, when you click "Submit", fruit=apple will be
> included in the params of your request.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/ga-dc/wdidc5-project3/issues/91#issuecomment-102185679
> .

## 

.: Gwen Mak :.
 http://www.silverlining.etsy.com/
