### ISSUE TITLE
Arguments error when running rails

### ISSUE THREAD

**Issue by britbrith4** [ga-dc/wdidc5-project3#92]
Rails won't run or migrate. Something to do with a file that I cannot find ....
![img_4557](https://cloud.githubusercontent.com/assets/11509416/7644345/9b80e088-fa71-11e4-8303-9e19b46a1ba0.jpg)

**Comment by RobertAKARobin** [comment]
Can you take a screenshot without using a camera? On a Mac, press `Cmd + Shift + 3` and it'll save a picture to your desktop. Press `Cmd + Shift + 4` and it'll give you a little crosshairs you can drag to select the amount of screen you want to capture.

**Comment by RobertAKARobin** [comment]
Also, did you remember to do `rails new appName -d postgresql`?

**Comment by mattscilipoti** [comment]
If you paste that error message about "Missing required arguments..." into google (including the names of the missing keys), I feel highly confident that you will get help on your problem.  I expect that you just added a gem that requires those keys.  Did this problem appear immediately after you added a gem to your Gemfile and restarted your server?  Have you followed the configuration instructions?

**Comment by mattscilipoti** [comment]
We recommend you use figaro to manage these config values.  It provides a way to manage it locally and a rake task to copy the config settings to heroku. https://github.com/laserlemon/figaro
