### ISSUE TITLE
Heroku Error: Need to get rid of jhint

### ISSUE THREAD

**Issue by JYamauchi** [ga-dc/wdidc5-project3#95]
I'm trying to setting up the Heroku and trying to rake db:migrate to heroku. I noticed some of gem files are not compatible with Heroku like Jshint. 
I did removed jshint from the gemfile and rakefile. It still gives me this error. 

``10:48:06-Hawaii~/ga/projects/project3_my_journal (myjournal)$ heroku run rake db:migrate --app myjournalz
Running `rake db:migrate` attached to terminal... up, run.6117
rake aborted!
LoadError: cannot load such file -- jshint/tasks
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `block in require'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:240:in `load_dependency'
/app/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.1/lib/active_support/dependencies.rb:274:in `require'
/app/Rakefile:7:in `<top (required)>'
(See full trace by running task with --trace)
10:48:21-Hawaii~/ga/projects/project3_my_journal (myjournal)$`

**Comment by RobertAKARobin** [comment]
You need to run `bundle install` to remove `jshint` from your `Gemfile.lock`

**Comment by RobertAKARobin** [comment]
...or you could just manually delete jshint from `Gemfile.lock`. Either way.

**Comment by JYamauchi** [comment]
I checked and jshint wasn't there. It still didn't work. I will use localhost for the sciencefair.

**Comment by RobertAKARobin** [comment]
Hm. It's still giving you some error about JSHint? And using `localhost` is fine!
