### ISSUE TITLE
Two of three fonts not working in Heroku

### ISSUE THREAD

**Issue by lmdragun** [ga-dc/wdidc5-project3#97]
I have three custom fonts on my app, one is working on Heroku but no matter what I try the other two I'm using are not. I've changed the code a bunch of times and precompiled assets, I've changed the formats to fit with google search results, etc.

The code that's working follows (I copied and pasted and changed names/url to fit the other fonts, but that didn't work)

```
@font-face {
  font-family: 'Suplexmentary Comic NC';
  src: url(/assets/sup/SuplexmentaryComicNC.eot);
  src: url(/assets/sup/SuplexmentaryComicNC.eot?#iefix) format("embedded-opentype"),
    url(/assets/sup/SuplexmentaryComicNC.ttf) format("truetype"),
    url(/assets/sup/SuplexmentaryComicNC.woff) format("woff"),
    url(/assets/sup/SuplexmentaryComicNC.svg#icofonts) format("svg");
  font-weight: normal;
  font-style: normal;
}
```

**Comment by RobertAKARobin** [comment]
http://stackoverflow.com/questions/19323563/heroku-font-assets-not-working

**Comment by RobertAKARobin** [comment]
Looks like just some small textual changes.

**Comment by lmdragun** [comment]
Already tried that.

**Comment by RobertAKARobin** [comment]
I'm not seeing it in the code you pasted above. You have:

```
src: url(/assets/sup/SuplexmentaryComicNC.eot);
```

as opposed to:

```
src: font-url("/assets/sup/SuplexmentaryComicNC.eot");
```

**Comment by RobertAKARobin** [comment]
Failing that, you could also just put an inline stylesheet in your `application.html.erb`.
